services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proteomics
    ports:
      - 5432:5432
    volumes:
      - /mnt/data/postgres-data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.staging
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend


  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.staging
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    extra_hosts:
    - "host.docker.internal:host-gateway"
