---
- name: Git clone s4pred
  ansible.builtin.git:
    repo: git@github.com:psipred/s4pred.git
    dest: "{{ s4pred_dir }}"
    accept_hostkey: yes
    key_file: /home/ec2-user/.ssh/david_student_key

    
- name: Download the weights
  get_url:
    url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz"
    dest: "{{ s4pred_dir }}/weights.tar.gz"
    mode: 0755
  register: download_weights
    

- name: Extract the weights
  unarchive:
    src: "{{ s4pred_dir }}/weights.tar.gz"
    dest: "{{ s4pred_dir }}"
    remote_src: yes
    creates: "{{ s4pred_dir }}/weights"

- name: Clean up
  file:
    path: "{{ s4pred_dir }}/weights.tar.gz"
    state: absent
