- name: send private key to instance
  copy:
    src: /home/ec2-user/.ssh/david_student_key
    dest: /home/ec2-user/.ssh/david_student_key
    owner: ec2-user
    group: ec2-user
    mode: 0600


- name: wake up ssh-agent and add david_student_key
  shell: |
    eval `ssh-agent -s`
    ssh-add /home/ec2-user/.ssh/david_student_key

- name: clone git repo
  git:
    repo: '{{ git_repo }}'
    dest: "{{ repo_dir }}"
    accept_hostkey: yes
    key_file: /home/ec2-user/.ssh/david_student_key


- name: create environment
  shell: |
    cd {{ repo_dir }} && \
    python3 -m venv venv

- name: Change ownership of repo
  become: yes
  file:
    path: "{{ repo_dir }}"
    owner: ec2-user
    group: ec2-user
    recurse: yes


