---

- name: Update git repo
  git:
    repo: '{{ git_repo }}'
    dest: "{{ repo_dir }}"
    accept_hostkey: yes
    key_file: /home/ec2-user/.ssh/david_student_key


- name: install requirements
  shell: |
    cd {{ repo_dir }} && \
    source venv/bin/activate && \
    pip install pip --upgrade && \
    cd {{ repo_dir }}/pipeline && \
    TMPDIR=/mnt/data pip install . --no-cache --cache-dir=/mnt/data/pip_cache --no-cache
