---

- name: Change owner of repo dir
  file:
    path: "{{ repo_dir }}"
    owner: ec2-user
    group: ec2-user
    state: directory
    recurse: yes

- name: Update git repo
  git:
    repo: '{{ git_repo }}'
    dest: "{{ repo_dir }}"
    accept_hostkey: yes
    key_file: /home/ec2-user/.ssh/david_student_key

- name: Update env vars 
  shell: |
    cd {{ repo_dir }} && ./scripts/setup_local_env.sh --hostname {{ groups['client'][0] }}

- name: install requirements
  shell: |
    cd {{ repo_dir }} && \
    source venv/bin/activate && \
    pip install pip --upgrade && \
    cd {{ repo_dir }}/pipeline && \
    TMPDIR=/mnt/data pip install . --no-cache --cache-dir=/mnt/data/pip_cache --no-cache
