- name: install postgres
  ansible.builtin.dnf:
    name: postgresql
    state: latest

- name: Find out if postgres is initilialised
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data"
  register: postgres_data

- name: initalisedb
  shell: "/usr/bin/postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: install firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: latest