---

- name: Install Java 8
  yum:
    name: "{{ java_package }}"
    state: present
  
- name: Verify Java 8 installation
  command: java -version
  register: java_version

- name: Print Java 8 version
  debug:
    msg: "{{ java_version.stdout }}"