---

- name: Verify if spark is already installed
  stat:
    path: "{{ spark_install_dir }}/bin/spark-shell"
  register: spark_installation

- name: Log spark installation status
  debug:
    msg: "Spark is already installed, skipping installation"
  when: spark_installation.stat.exists == True

- name: Download Spark
  become: true
  get_url:
    url: "{{ spark_download_url }}"
    dest: "{{ spark_download_dest }}"
    mode: 0755
    validate_certs: no
  when: spark_installation.stat.exists == False


- name: Change owner of Spark installation directory
  become: true
  file:
    path: "{{ spark_install_dir }}/spark"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
    mode: 0755
    recurse: yes

- name: Extract Spark
  become: true
  unarchive:
    src: "{{ spark_download_dest }}"
    dest: "{{ spark_install_dir }}"
    remote_src: yes
    creates: "{{ spark_install_dir }}/bin/spark-shell"

- name: Remove Spark tarball if it exists
  become: true
  file:
    path: "{{ spark_download_dest }}"
    state: absent
  when: spark_installation.stat.exists == False

- name: Change spark name folder
  become: true
  command: mv {{ spark_install_dir }}/{{ spark_folder_name }} {{ spark_install_dir }}/spark
  when: spark_installation.stat.exists == False
  
- name: Set Spark environment variables in ~/.bashrc
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
    state: present
  with_items:
    - "export SPARK_HOME={{ spark_install_dir }}/spark"
    - "export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin"
  when: spark_installation.stat.exists == False

- name: Source ~/.bashrc
  shell: source ~/.bashrc

- name: Check Spark version
  become: true
  command: "{{ spark_install_dir }}/spark/bin/spark-shell --version"
  register: spark_version

- name: Print Spark version
  debug:
    msg: "{{ spark_version.stdout }}"

