- name: Create workers file
  become: true
  file:
    path: "{{ spark_install_dir }}/spark/conf/workers"
    state: touch
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
    mode: 0644
    
- name: Add workers list
  lineinfile:
    dest: "{{ spark_install_dir }}/spark/conf/workers"
    line: "{{ item }}"
    state: present
  with_items:
    - "ec2-user@{{ groups['clusters'][0] }}"
    - "ec2-user@{{ groups['clusters'][1] }}"
    - "ec2-user@{{ groups['clusters'][2] }}"
    - "ec2-user@{{ groups['clusters'][3] }}"