
- name: Give private key to master
  copy:
    src: "{{ ssh_private_key }}"
    dest: "{{ ssh_private_key }}"
    owner: "{{ spark_user }}"
    group: "{{ spark_group }}"
    mode: 0600


- name: wake up ssh-agent and add private_key
  shell: |
    eval `ssh-agent -s`
    ssh-add {{ ssh_private_key }}


- name: SSH to workers and say yes to add them to known hosts
  become: true
  command: ssh -o StrictHostKeyChecking=no -i {{ ssh_private_key }} ec2-user@{{ item }} "echo 'yes' > /dev/null"
  with_items:
    - "{{ groups['clusters'] }}"


- name: ssh test to cluster
  shell: |
    ssh -i {{ ssh_private_key }} -o StrictHostKeyChecking=no ec2-user@{{ item }} echo "ssh test to {{ item }} successful"
  with_items: "{{ groups['clusters'] }}"


