- name: Main Playbook
  hosts: clusters
  vars:
    my_region: eu-west-2
    git_repo: git@github.com:davidfrisch/dataEng1CW.git
    ansible_python_interpreter: /usr/bin/python3.11
    # hh_suite vars
    hh_suite_dir: /mnt/data/programs/hh-suite
    hh_suite_file: hhsuite-3.3.0-AVX2-Linux.tar.gz
    hh_suite_url: https://github.com/soedinglab/hh-suite/releases/download/v3.3.0/hhsuite-3.3.0-AVX2-Linux.tar.gz
    # s4pred vars
    s4pred_dir: /mnt/data/programs/s4pred


    ###
  module_defaults:
    community.aws.ec2_instance_info:
      region: '{{ my_region }}'
    amazon.aws.ec2_vpc_net_info:
      region: '{{ my_region }}'
    amazon.aws.ec2_vol:
      region: '{{ my_region }}'


  tasks:
    # add spark role
    - name: Add spark role
      import_role:
        name: spark_role
    # - name: Install Python 3.11
    #   include_tasks: tasks/install_python311.yml

    # - name: Install Repo
    #   include_tasks: tasks/install_repo.yml
    # - include_tasks: tasks/send_pdb70.yml
    # - include_tasks: tasks/download_pdb70.yml
    #  - include_tasks: tasks/install_hhsearch.yml
      - include_tasks: tasks/install_s4pred.yml
    # - include_tasks: install_spark.yml
    
