---

- name: Master Playbook
  hosts: client
  become: true

  tasks:
    - name: Include common role
      import_role:
        name: common
    
    - name: Include master role
      import_role:
        name: master

- name: Cluster Playbook
  hosts: clusters
  become: true

  tasks:
    - name: Include common role
      import_role:
        name: common
    
    - name: Include cluster role
      import_role:
        name: cluster

