---

- name: Master Playbook
  hosts: client
  become: true

  tasks:
    - include_vars: vars.yml
    - include_vars: custom_vars.yml
    
    - name: Include common role
      import_role:
        name: common
    
    - name: Include master role
      import_role:
        name: master

    - name: Echo spark master that will be used
      debug:
        msg: "Spark master is spark://{{ groups['client'][0] }}:7077"


- name: Cluster Playbook
  hosts: clusters
  become: true

  tasks:
    - include_vars: vars.yml

    - name: Include common role
      import_role:
        name: common
    
    - name: Include cluster role
      import_role:
        name: cluster

    - name: Echo spark master that will be used
      debug:
        msg: "Spark master is spark://{{ groups['client'][0] }}:7077"
