
- name: Cluster Playbook
  hosts: clusters
  become: true

  tasks:
    - include_vars: vars.yml
    - include_vars: custom_vars.yml

    - name: Include common role
      import_role:
        name: common

        
- name: Master Playbook
  hosts: client
  become: true

  tasks:
    - include_vars: vars.yml
    - include_vars: custom_vars.yml
    
    - name: Include common role
      import_role:
        name: common
    
    - name: Include master role
      import_role:
        name: master
    
    - name: Include pdb70 role
      import_role:
        name: pdb70







