- name: Stop Cluster Playbook
  hosts: client

  tasks:
    - include_vars: vars.yml
    - name: Stop spark and workers set in its workers file
      command: "{{ spark_install_dir}}/spark/sbin/stop-all.sh"

    - name: Docker compose down
      shell:  cd {{ repo_dir }} && docker compose down

    - name: Stop flask app
      shell: "pkill -f 'gunicorn -b 0.0.0.0:5000 flask_app:app'"
      # Ignore error because the flask app may not be running
      ignore_errors: true
      async: 0
      poll: 0

- name: Clean up Cache
  hosts: client, clusters

  tasks:
    - name: Clean cache
      become: true
      shell: sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
