- name: My first playbook
  hosts: mymachines
  become: true
  become_user: root
  tasks:
    - name: install postgres
      ansible.builtin.dnf:
        name: postgresql
        state: latest
    
    - name: install postgres-server components
      ansible.builtin.dnf:
        name: postgresql-server, postgresql-contrib
        state: latest
    
    - name: initialise DB
      shell: "/usr/bin/postgresql-setup initdb"

    - name: start postgres
      ansible.builtin.service:
        name: postgresql
        state: started